### ISSUE TITLE
勝手に死ぬことが多い

### ISSUE THREAD

**Issue by masui** [stkay/GyaonAndroid#10]
使ってなくても突然死する

**Comment by Hikaru-Ito** [comment]
おそらく、ServiceがOSによってkillされてしまうからでしょう。
OSからkill対象にされにくくするために、動作中であることをOSに明示する必要があります。
具体的には、Notification + startForeground を使って、Serviceをforegroundで動作するように実装すると、killされにくくなります。

https://developer.android.com/reference/android/app/Service.html#startForeground(int,android.app.Notification)

また、

https://github.com/stkay/GyaonAndroid/blob/1e18d4e82697b1d5f6a6719e1267affef7161d3f/app/src/main/java/com/stkay/gyaonandroid/MainActivity.java#L97-L100

```
    protected void onDestroy() {
        super.onDestroy();
        stopService();
    }
```

ここで、Activityが死ぬとServiceを止めるように実装していますが、
Service単体で録音・アップロード等の処理が完結するなら（今回の場合はOK）、stopServiceしなければ、Applicationが終了してもServiceは終了しません。

**Comment by isSatake** [comment]
> Service単体で録音・アップロード等の処理が完結するなら（今回の場合はOK）、stopServiceしなければ、Applicationが終了してもServiceは終了しません。

Serviceを終了させたいときはどうするの？

**Comment by Hikaru-Ito** [comment]
Service自身が`stopService`を呼んで自殺させればいいです。
NotificationをcustomLayoutでつくって、キャンセルボタンとかを設置して、タップすると、
`stopFroground`と`stopService`を呼ぶようにするといいです。

**Comment by Hikaru-Ito** [comment]
すいません、`stopService`呼べば`stopForeground`は必要ないですね

**Comment by isSatake** [comment]
![](https://emoji.slack-edge.com/T02AFRBD9/naruhodo/4171dc47044f6787.png)
